AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda-funksjon for 책 generere AI-bilder basert p책 en prompt og lagre i S3.

Globals:
  Function:
    Timeout: 30  # Request timer ut etter 30 sek. juster i tilfelle genereringen tar mer tid
    MemorySize: 256
    LoggingConfig:
      LogFormat: JSON

Resources:
  GenerateImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./                   # ser i samme mappe
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          BUCKET_NAME: "pgr301-couch-explorers" # her defineres s3 bucket navn
          CANDIDATE_PREFIX: "9"
      Policies:         
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - "s3:PutObject"  # tillatelse for 책 skrive til bucket
            Resource:
              - "arn:aws:s3:::pgr301-couch-explorers/9/*"
        - Statement:
            Effect: Allow
            Action:
              - "bedrock:InvokeModel"  # tillatelse for 책 kalle tjenesten og generere bilder med Titan-modellen
            Resource: "*"
      Events:
        GenerateImageAPI:
          Type: Api
          Properties:
            Path: /generate-image
            Method: post

Outputs:
  GenerateImageApiUrl:
    Description: "API Gateway endpoint URL for image generation"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-image"
