AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda-funksjon for å generere AI-bilder basert på en prompt og lagre i S3.

Globals:
  Function:
    Timeout: 10  # Justerer Timeout i tilfelle genereringen tar mer tid
    MemorySize: 256
    LoggingConfig:
      LogFormat: JSON

Resources:
  GenerateImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          BUCKET_NAME: "pgr301-couch-explorers"
          CANDIDATE_PREFIX: "9"
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - "s3:PutObject"
            Resource:
              - "arn:aws:s3:::pgr301-couch-explorers/9/*"
        - Statement:
            Effect: Allow
            Action:
              - "bedrock:InvokeModel"
            Resource: "*"
      Events:
        GenerateImageAPI:
          Type: Api
          Properties:
            Path: /generate-image
            Method: post

Outputs:
  GenerateImageApiUrl:
    Description: "API Gateway endpoint URL for image generation"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-image"
